title: Gabriel Marvin
footer_text: I love meeting new people. If you find interest in something I do, send me an email or message me on Twitter
url: https://www.gabrielmarvin.com
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - posts
  - projects

github_username:   Marvin8or
linkedin_username: gabrielmarvin
email: gabrielmarvin18@gmail.com
